kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-streaming-admin
  labels:
    streaming.knative.dev/release: devel
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      streaming.knative.dev/controller: "true"
rules: [] # Rules are automatically filled in by the controller manager.
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-streaming-core
  labels:
    streaming.knative.dev/release: devel
    streaming.knative.dev/controller: "true"
rules:
  - apiGroups: [""]
    resources: ["configmaps", "services", "secrets", "events"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/finalizers"] # finalizers are needed for the owner reference of the webhook
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["streaming.knative.dev"]
    resources: ["*"]
    verbs: ["get", "list", "create", "update", "delete", "deletecollection", "patch", "watch"]
